owner: parikshit-parspec # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: app.parspec.io
    url: https://app.parspec.io/
  - name: api.parspec.io
    url: https://api.parspec.io/admin/
  - name: wvproxy.parspec.io
    url: http://wvproxy.parspec.io/
  - name: search.parspec.io
    url: https://search.parspec.io/admin/
  - name: parspec-prod-IM-UIUX-3
    url: http://ec2-18-188-222-89.us-east-2.compute.amazonaws.com/health
  - name: parspec-prod-IM-UIUX-4
    url: http://ec2-18-220-113-165.us-east-2.compute.amazonaws.com/health
  - name: parspec-deep-learning-inference-GPU
    url: http://3.20.227.85:8501/v1/models/bert_v3:predict
    method: POST
    headers:
      - "Accept: */*"
      - "Content-Length: 36"
      - "Content-Type: application/x-www-form-urlencoded"
    body: '{"instances": ["1.0", "2.0", "5.0"]}'
  # - name: ej2.parspec.io
    # url: https://ej2.parspec.io/health

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://app.parspec.io/assets/images/sidenav/logo.svg
  name: Parspec Status
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  faviconSvg: https://app.parspec.io/assets/images/sidenav/logo.svg

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 4 * * *"

i18n:
  allSystemsOperational: All systems are operational 🥳 🎉

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
