owner: parikshit-parspec # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: app.parspec.io
    url: https://app.parspec.io/
  - name: review.parspec.io
    url: https://review.parspec.io/
  - name: api.parspec.io
    url: https://api.parspec.io/health
  - name: wvproxy.parspec.io
    url: http://wvproxy.parspec.io/marco
  - name: search.parspec.io
    url: https://search.parspec.io/health
  - name: sonic
    url: https://api.parspec.io/marco
  - name: arc
    url: https://arc.parspec.io/marco
  - name: row-detection
    url: http://row-detect.parspec.io/v1/models/header_detection:predict
    method: POST
    headers:
      - "Accept: */*"
      - "Content-Length: 23"
      - "Content-Type: application/x-www-form-urlencoded"
    body: '{"instances": ["type"]}'
  - name: col-detection
    url: http:/col-detect.parspec.io/v1/models/col_detection:predict
    method: POST
    headers:
      - "Accept: */*"
      - "Content-Length: 23"
      - "Content-Type: application/x-www-form-urlencoded"
    body: '{"instances": ["type"]}'
  - name: pdf-attr-extraction
    url: https://ai-prod.parspec-cp.io/health
  - name: ej2.parspec.io
    url: https://ej2.parspec.io/health
  - name: parspec-hubspot-prod
    url: https://hubspot.parspec.io/health
  - name: FE events
    url: https://fe-event-service.parspec.io/healthz
  - name: Data ingestion service
    url: https://platform.parspec.io/ingestion-service/api/v1/marco
  - name: 🔌 parspec connector
    url: https://apim.workato.com/parspecdev/connector-health-vv1/parspec-connector
    headers:
      - "api-token: $RECIPE_TOKEN"
  - name: Inventory Service
    url: https://inventory.parspec.io/inventory-service/marco

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://app.parspec.io/assets/images/sidenav/logo.svg
  name: Parspec Status
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  faviconSvg: https://app.parspec.io/assets/images/sidenav/logo.svg
  theme: light

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 4 * * *"

i18n:
  allSystemsOperational: All systems are operational 🥳 🎉

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
